version: '3'
services:
  db:
    platform: linux/amd64
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    container_name: postgres
    networks:
      - practise

  pgadmin:
    platform: linux/amd64
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:  
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
    networks:
      - practise
  
  
  api:
    platform: linux/amd64
    build: .
    command: uvicorn main:app --port 8080 --host 0.0.0.0 --reload
    volumes:
      - .:/api
    depends_on:
      - db
    ports:
      - ${APP_PORT}:${CONTAINER_PORT}
    restart: unless-stopped
    container_name: api
    networks:
      - practise

  redis:
    platform: linux/amd64
    image: redis:${REDIS_VERSION}
    volumes:
      - redis_data:/data
    container_name: redis
    networks:
      - practise
volumes:
  postgresql-data:
  redis_data:

networks:
  practise: