version: '3'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    container_name: postgres
    networks:
      - practise

  api:
    build: .
    command: uvicorn main:app --port 8080 --host 0.0.0.0 --reload
    depends_on:
      - db
    ports:
      - ${APP_PORT}:${CONTAINER_PORT}
    restart: on-failure
    container_name: fastapi
    networks:
      - practise

  redis:
    image: redis:${REDIS_VERSION}
    volumes:
      - redis_data:/data
    container_name: redis
    networks:
      - practise
volumes:
  postgresql-data:
  redis_data:

networks:
  practise: