"""ondelete=autocascade

Revision ID: 097d2a38e5c7
Revises: 17cd394dee95
Create Date: 2022-10-25 16:20:40.045736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097d2a38e5c7'
down_revision = '17cd394dee95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invites_user_id_fkey', 'invites', type_='foreignkey')
    op.drop_constraint('invites_company_id_fkey', 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invites', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('members_user_id_fkey', 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_quiz_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quizzes_company_id_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_company_id_fkey', 'quizzes', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_quiz_id_fkey', 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key('members_user_id_fkey', 'members', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key('invites_company_id_fkey', 'invites', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('invites_user_id_fkey', 'invites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
