"""new 

Revision ID: 17cd394dee95
Revises: 8909800e29ed
Create Date: 2022-10-25 07:15:13.860470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cd394dee95'
down_revision = '8909800e29ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quizzes', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'company_id')
    # ### end Alembic commands ###
