"""changed naming

Revision ID: 2d57560ae86a
Revises: a14ecf41210f
Create Date: 2022-10-30 04:09:46.414527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d57560ae86a'
down_revision = 'a14ecf41210f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mean_results', sa.Column('last_time_solved', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('mean_results', 'date_solved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mean_results', sa.Column('date_solved', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('mean_results', 'last_time_solved')
    # ### end Alembic commands ###
