"""is_admin

Revision ID: 3a48a49c5604
Revises: 6543089f26a9
Create Date: 2022-10-24 11:14:09.171999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a48a49c5604'
down_revision = '6543089f26a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=True))
    op.drop_column('members', 'isadmin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('isadmin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('members', 'is_admin')
    # ### end Alembic commands ###
