"""new

Revision ID: 44f654bb2ce9
Revises: 66efab364095
Create Date: 2022-10-22 10:37:18.395440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f654bb2ce9'
down_revision = '66efab364095'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
