"""new

Revision ID: 66efab364095
Revises: 64fcd636754c
Create Date: 2022-10-22 10:27:23.449705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66efab364095'
down_revision = '64fcd636754c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
