"""new

Revision ID: 6af35bb303f2
Revises: 7d09d1e06ebc
Create Date: 2022-10-28 08:12:21.686189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af35bb303f2'
down_revision = '7d09d1e06ebc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('date_solved', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'date_solved')
    # ### end Alembic commands ###
