"""new 

Revision ID: 7d09d1e06ebc
Revises: be73786c3ff5
Create Date: 2022-10-26 16:05:11.562305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d09d1e06ebc'
down_revision = 'be73786c3ff5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
