"""new

Revision ID: 93214023fc46
Revises: 2d57560ae86a
Create Date: 2022-10-30 05:45:51.427336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93214023fc46'
down_revision = '2d57560ae86a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
