"""new

Revision ID: 9496aa195bf9
Revises: 6dd3075dfd8f
Create Date: 2022-10-21 12:06:00.522296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9496aa195bf9'
down_revision = '6dd3075dfd8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('companies_members_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('companies', 'members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('members', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key('companies_members_fkey', 'companies', 'users', ['members'], ['id'])
    op.drop_column('companies', 'owner_id')
    # ### end Alembic commands ###
