"""datetimefields

Revision ID: a14ecf41210f
Revises: 5c82a1a7deb1
Create Date: 2022-10-30 04:06:45.332327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14ecf41210f'
down_revision = '5c82a1a7deb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mean_results', sa.Column('first_time_solved', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('mean_results', sa.Column('date_solved', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mean_results', 'date_solved')
    op.drop_column('mean_results', 'first_time_solved')
    # ### end Alembic commands ###
