"""new

Revision ID: ade2b2d462e3
Revises: 1a418855c7fd
Create Date: 2022-10-22 04:09:25.860044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade2b2d462e3'
down_revision = '1a418855c7fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
