"""new_column

Revision ID: d49f6805b199
Revises: 93214023fc46
Create Date: 2022-10-30 05:53:19.114547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49f6805b199'
down_revision = '93214023fc46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('mean_result', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'mean_result')
    # ### end Alembic commands ###
